### ISSUE TITLE
【依頼】ChatSpace挙動確認

### ISSUE THREAD

**Issue by tadashi622** [tadashi622/chat-space#15]
#IPアドレス
3.20.161.142

よろしくお願いいたします。

**Comment by mo1015** [comment]
吉村さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

**○contents上部の見た目が見本と異なる（名前とアイコンの部分に色がかかっている、グループメンバー名の下の線の色が違う）
○投稿フォーム内の文字「type a message」が左に偏りすぎている
○画面を縮小したとき、Editボタン、投稿フォームのsendボタンと画像アイコンが見切れてしまう
○サイドバーのグループごとの間隔がとれていない**
<img width="663" alt="スクリーンショット_2020-04-05_17_56_23" src="https://user-images.githubusercontent.com/62644781/78471124-bd55a700-7769-11ea-8f10-979aed9ac898.png">



↓見本です
<img width="724" alt="スクリーンショット_2020-04-05_17_50_38" src="https://user-images.githubusercontent.com/62644781/78471008-c8f49e00-7768-11ea-9fc7-8db9a30b7b94.png">

○テキストと画像を同時に送信すると、テキストが投稿されない
○Sendボタンを2回押した時にアラートが出現しない

修正し次第、以下のChatSpace完了報告フォームに再度こちらのissueのURLを記載していただき提出お願いします！
※新しいissueを作っていただく必要はありません
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by tadashi622** [comment]
確認ありがとうございます。
修正しました。
再度、確認よろしくお願いいたします。
＃
3.20.161.142

**Comment by yasunamiura** [comment]
さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、前回の修正を確認できました！新たに以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
ログイン・サインアップ画面の配置のCSSを模範のとおり整えましょう。
現在のログイン
<img width="1103" alt="ChatSpace" src="https://user-images.githubusercontent.com/52514431/78521474-e6774580-7804-11ea-8045-6f93bffc0f8d.png">
模範
<img width="1103" alt="ChatSpaceSample" src="https://user-images.githubusercontent.com/52514431/78521512-0575d780-7805-11ea-9383-ea87d9162e3b.png">
現在のサインアップ
<img width="1031" alt="ChatSpace" src="https://user-images.githubusercontent.com/52514431/78521561-39e99380-7805-11ea-8456-d10a3fefa012.png">
模範
<img width="1055" alt="ChatSpaceSample" src="https://user-images.githubusercontent.com/52514431/78521576-4a9a0980-7805-11ea-8e5d-f413d97e6487.png">


修正し次第、以下のChatSpace完了報告フォームに再度こちらのissueのURLを記載していただき提出お願いします！
※新しいissueを作っていただく必要はありません
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by tadashi622** [comment]
確認ありがとうございます。
修正しました。
再度、確認よろしくお願いいたします。

＃3.20.161.142

**Comment by yasunamiura** [comment]
ご提出ありがとうございます！
確認させて頂きましたが、修正箇所ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！
